# -*- coding: utf-8 -*-
"""Text_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQmYVPqieZuiuOqZ8vjuQ18fGHd0UEnq
"""

!pip install transformers
!pip intsall torch
!pip install gradio
!pip install datasets

"""loading the pretarined model and tokenizer

"""

from transformers import T5Tokenizer, T5ForConditionalGeneration
model_name = 't5-base'
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

"""Define the summarization function"""

def summarize(text):
    inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", max_length=1024, truncation=True)
    summary_ids = model.generate(inputs, max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

"""build gradio interface"""

import gradio as gr

iface = gr.Interface(
    fn=summarize,
    inputs="text",
    outputs="text",
    title="Text Summarization with T5",
    description="Enter text to get a summarized version using the T5 model."
)

iface.launch()